[package]
name = "alga_derive_test"
version = "0.1.0"
authors = ["Wadelma <delma@del.ma>"]

[dependencies]
alga = { path = "../alga", default_features = false }
alga_derive = { path = "../alga_derive" }
compiletest_rs = "0.3"
